"""Independent AI and SOAR schema

Revision ID: 0001
Revises:
"""

from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_proposals",
        sa.Column("proposal_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("incident_id", sa.String(length=128), nullable=False),
        sa.Column("action_type", sa.String(length=60), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("approved_by", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("playbook_id", sa.String(length=128), nullable=False),
        sa.Column("playbook_snapshot", sa.JSON(), nullable=False),
        sa.Column("rollback_available", sa.Boolean(), nullable=False),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("proposal_id"),
    )
    op.create_index(op.f("ix_action_proposals_incident_id"), "action_proposals", ["incident_id"], unique=False)
    op.create_index(op.f("ix_action_proposals_tenant_id"), "action_proposals", ["tenant_id"], unique=False)
    op.create_table(
        "ai_runs",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("incident_id", sa.String(length=128), nullable=False),
        sa.Column("requested_by", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("validation_status", sa.String(length=40), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("context_snapshot", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(op.f("ix_ai_runs_incident_id"), "ai_runs", ["incident_id"], unique=False)
    op.create_index(op.f("ix_ai_runs_tenant_id"), "ai_runs", ["tenant_id"], unique=False)
    op.create_table(
        "service_users",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "name"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_service_users_tenant_id"), "service_users", ["tenant_id"], unique=False)
    op.create_table(
        "action_approvals",
        sa.Column("proposal_id", sa.String(length=128), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("proposal_id"),
    )
    op.create_table(
        "action_audit",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("proposal_id", sa.String(length=128), nullable=True),
        sa.Column("actor", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_audit_proposal_id"), "action_audit", ["proposal_id"], unique=False)
    op.create_index(op.f("ix_action_audit_tenant_id"), "action_audit", ["tenant_id"], unique=False)
    op.create_table(
        "action_executions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("proposal_id", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("executor", sa.String(length=40), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("proposal_id", "operation"),
    )
    op.create_index(op.f("ix_action_executions_proposal_id"), "action_executions", ["proposal_id"], unique=False)
    op.create_table(
        "ai_analyses",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.Column("validation", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_table(
        "ai_steps",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=80), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.Column("tool_name", sa.String(length=80), nullable=False),
        sa.Column("output_ref", sa.String(length=256), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ai_runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence"),
    )
    op.create_index(op.f("ix_ai_steps_run_id"), "ai_steps", ["run_id"], unique=False)
    op.create_table(
        "simulated_effects",
        sa.Column("proposal_id", sa.String(length=128), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("target", sa.String(length=128), nullable=False),
        sa.Column("action_type", sa.String(length=60), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["action_proposals.proposal_id"],
        ),
        sa.PrimaryKeyConstraint("proposal_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("simulated_effects")
    op.drop_index(op.f("ix_ai_steps_run_id"), table_name="ai_steps")
    op.drop_table("ai_steps")
    op.drop_table("ai_analyses")
    op.drop_index(op.f("ix_action_executions_proposal_id"), table_name="action_executions")
    op.drop_table("action_executions")
    op.drop_index(op.f("ix_action_audit_tenant_id"), table_name="action_audit")
    op.drop_index(op.f("ix_action_audit_proposal_id"), table_name="action_audit")
    op.drop_table("action_audit")
    op.drop_table("action_approvals")
    op.drop_index(op.f("ix_service_users_tenant_id"), table_name="service_users")
    op.drop_table("service_users")
    op.drop_index(op.f("ix_ai_runs_tenant_id"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_incident_id"), table_name="ai_runs")
    op.drop_table("ai_runs")
    op.drop_index(op.f("ix_action_proposals_tenant_id"), table_name="action_proposals")
    op.drop_index(op.f("ix_action_proposals_incident_id"), table_name="action_proposals")
    op.drop_table("action_proposals")
    # ### end Alembic commands ###
