import {api, routes as R, escapeHTML as e, can, actionLabel} from './api.mjs';

const root=document.querySelector('#app');
let user=null, page='overview', offset=0;
const names={overview:'Overview',incidents:'Incidents',events:'Evidence / Alerts',runs:'AI Investigations',actions:'SOAR Actions',playbooks:'Playbooks',assets:'Assets',integrations:'Integrations',audit:'Audit',users:'Users & Roles',settings:'Settings',health:'System Health'};
const descriptions={overview:'Your investigation workspace. Every finding starts with evidence.',incidents:'Investigate normalized incidents with their source provenance intact.',events:'Source-attributed evidence. Unknown telemetry stays unknown.',runs:'Structured analysis with independently checked evidence citations.',actions:'Human decisions, durable operation claims, verified outcomes.',playbooks:'Reviewed workflows with mandatory approval and restoration steps.',assets:'Tenant-scoped inventory and protected-target metadata.',integrations:'Connect sources to your product-owned evidence store.',audit:'A durable record of identity, ingestion, investigation and response.',users:'Separate responsibilities. Each person has one explicit role.',settings:'Deployment configuration and safety boundaries.',health:'Readiness signals are not proof of inference or live containment.'};
const badge=v=>`<span class="badge ${e(String(v??'UNKNOWN').toLowerCase().replaceAll('_','-').replaceAll(' ','-'))}">${e(v)}</span>`;
const date=v=>v?new Date(v).toLocaleString():'UNKNOWN';
const pretty=v=>`<pre>${e(JSON.stringify(v,null,2))}</pre>`;
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.style.display='block';setTimeout(()=>el.style.display='none',6000);}
function empty(title,description){return `<div class="empty"><strong>${e(title)}</strong>${e(description)}</div>`;}
function button(text,id,primary=false){return `<button class="btn ${primary?'primary':''}" data-do="${e(id)}">${e(text)}</button>`;}
function shell(){
 root.innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span>◈</span> SentinelZone<small>AI / SOAR WORKSPACE</small></div><div class="nav-label">Investigate & respond</div><nav>${Object.entries(names).filter(([k])=>!['users','settings'].includes(k)||user.role==='admin').map(([k,v])=>`<a href="#${k}" class="${page===k?'active':''}">${e(v)}</a>`).join('')}</nav><div class="sidebar-foot"><span class="dot"></span>Independent by design<br>v0.30.0-rc.1 · Release candidate<br>Human approval always required</div></aside><div><header class="topbar"><div class="small muted">WORKSPACE <span class="mono">/ ${e(user.tenant_id)}</span></div><div class="identity">${badge('DRY RUN')}<span>${e(user.name)} <small>· ${e(user.role)}</small></span><button class="btn" id="logout">Sign out</button></div></header><main class="content"><div class="title-row"><div><div class="eyebrow">SentinelZone / ${e(names[page])}</div><h1>${e(names[page])}</h1><p class="tagline">${e(descriptions[page])}</p></div><div class="actions" id="page-actions"></div></div><div id="view"><div class="loading">Loading…</div></div></main></div></div><dialog id="detail"></dialog>`;
 document.querySelector('#logout').onclick=async()=>{try{await api(R.logout,{method:'POST'});user=null;await authScreen();}catch(err){toast(err.message);}};
}
function modal(title,body){const d=document.querySelector('#detail');d.innerHTML=`<div class="dialog-head"><h2>${e(title)}</h2><button class="btn" id="close-detail" aria-label="Close dialog">Close</button></div><div id="dialog-body">${body}</div>`;d.showModal();d.querySelector('#close-detail').onclick=()=>d.close();return d;}
function errorBox(err){return `<div class="notice amber">${e(err.message)}. Refresh to inspect current state before repeating a request.</div>`;}
async function runButton(btn,fn){btn.disabled=true;try{await fn();}catch(err){toast(err.message);}finally{btn.disabled=false;}}
async function authScreen(){
 let available=false;try{available=(await api(R.bootstrapStatus)).available;}catch{}
 root.innerHTML=`<main class="auth panel"><div class="brand"><span>◈</span> SentinelZone<small>AI / SOAR</small></div><div class="eyebrow">Independent security operations</div><h1>${available?'Create your workspace':'Welcome back'}</h1><p class="muted">${available?'Bootstrap the first administrator using the one-time secret from your private configuration.':'Sign in with your own account to investigate and review actions.'}</p><form id="auth-form"><label>Tenant ID<input name="tenant_id" autocomplete="organization" required pattern="[A-Za-z0-9_.:-]+" maxlength="128"></label><label>Username<input name="name" autocomplete="username" required pattern="[A-Za-z0-9_.:-]+" maxlength="128"></label><label>Password<input name="password" type="password" autocomplete="${available?'new-password':'current-password'}" required minlength="${available?14:1}" maxlength="256"></label>${available?'<label>Bootstrap secret<input name="bootstrap_token" type="password" autocomplete="off" required minlength="32"></label>':''}<div id="auth-error" class="error" role="alert"></div><button class="btn primary wide">${available?'Create first admin':'Sign in'}</button></form><div class="notice small">Fresh installations use DRY RUN. Simulations never change a firewall or endpoint.</div></main>`;
 document.querySelector('#auth-form').onsubmit=async ev=>{ev.preventDefault();const f=ev.currentTarget;const btn=f.querySelector('button');btn.disabled=true;try{const data=Object.fromEntries(new FormData(f));await api(available?R.bootstrap:R.login,{method:'POST',body:data});f.reset();if(available){toast('Admin created. Sign in to manage users.');await authScreen();}else{user=(await api(R.me)).user;await navigate();}}catch(err){document.querySelector('#auth-error').textContent=err.message;}finally{btn.disabled=false;}};
}
async function navigate(){
 page=location.hash.slice(1) in names?location.hash.slice(1):'overview';offset=0;shell();await load();
}
async function load(){
 const view=document.querySelector('#view'), actions=document.querySelector('#page-actions');
 try{
 if(page==='overview'){
   const [o,inc]=await Promise.all([api(R.overview),api(R.incidents+'?limit=5')]);
   actions.innerHTML=can(user.role,'investigate')?button('Load TEST exercise','demo'):'';
   view.innerHTML=`<div class="notice"><strong>Response is in simulation mode.</strong> Every action requires an analyst proposal and independent operator approval.</div><div class="cards">${[['incidents','Incidents'],['events','Evidence records'],['ai_runs','AI investigations'],['actions','SOAR proposals']].map(([k,n])=>`<div class="card"><div class="metric-label">${n}</div><div class="metric">${o.counts[k]}</div><div class="count-note">Current tenant · all data modes</div></div>`).join('')}</div><div class="two-col"><section class="panel"><div class="panel-head"><h2>Recent incidents</h2><a href="#incidents">View all →</a></div>${inc.items.length?incidentTable(inc.items):empty('Ready for your first evidence','Ingest normalized events and link them to an incident, or load a TEST exercise as an Analyst.')}</section><section class="panel"><div class="eyebrow">A deliberate response</div><h2 style="margin-top:10px">Evidence to decision</h2><ol class="steps"><li><strong>Collect and investigate</strong><small>Bounded, redacted evidence. Validated citations.</small></li><li><strong>Propose with context</strong><small>An Analyst chooses an action and target.</small></li><li><strong>Approve independently</strong><small>A different Operator reviews the proposal.</small></li><li><strong>Execute, verify, restore</strong><small>DRY RUN results remain clearly labeled.</small></li></ol></section></div><div class="notice amber small">Citation validation checks membership and scope. It does not prove an AI conclusion is correct. Human review is required.</div>`;
 }else if(['incidents','events','runs','actions','audit','assets','users'].includes(page)){
   const data=await api(R[page]+`?limit=50&offset=${offset}`);
   actions.innerHTML=(page==='incidents'&&can(user.role,'investigate')?button('Ingest incident','ingestIncidents'):page==='events'&&can(user.role,'investigate')?button('Ingest evidence','ingestEvents'):page==='assets'&&can(user.role,'manage')?button('Register asset','asset',true):page==='users'?button('Create user','user',true):'');
   const tables={incidents:incidentTable,events:eventTable,runs:runTable,actions:actionTable,audit:auditTable,assets:assetTable,users:userTable};
   view.innerHTML=`<section class="panel">${data.items.length?tables[page](data.items):empty('No records yet','Records appear here when your tenant begins using this workspace.')}</section><div class="toolbar"><button class="btn" id="previous" ${offset===0?'disabled':''}>← Previous</button><span class="muted small">${data.items.length} records · offset ${offset}</span><button class="btn" id="next" ${data.next_offset==null?'disabled':''}>Next →</button></div>`;
   document.querySelector('#previous').onclick=()=>{offset=Math.max(0,offset-50);load();};document.querySelector('#next').onclick=()=>{offset=data.next_offset;load();};
 }else if(page==='playbooks'){
   const data=await api(R.playbooks);view.innerHTML=`<div class="grid">${data.items.map(b=>`<article class="panel"><div class="eyebrow">${e(b.id)} · v${e(b.version)}</div><h2>${e(b.name)}</h2>${badge(b.action_type)}<div class="flow">${b.steps.map(s=>`<span>${e(s.action)}</span>`).join('<b>→</b>')}</div><p class="small muted">The backend validates step ordering and pins this workflow to each proposal.</p></article>`).join('')}</div>`;
 }else if(page==='integrations'){
   const data=await api(R.integrations);view.innerHTML=`<div class="grid">${data.items.map(i=>`<article class="panel"><div class="panel-head"><h2>${e(i.id)}</h2>${badge(i.status)}</div><p class="muted">${e(i.scope)}</p><p class="small">${i.id==='generic_rest'||i.id==='webhook'?'POST /v1/ingest/events · POST /v1/ingest/incidents':'See CONNECTORS.md for setup and verification gates.'}</p></article>`).join('')}</div><div class="notice amber">Vendor mocks do not prove live interoperability. Unimplemented executors remain disabled.</div>`;
 }else if(page==='settings'){
   const data=await api(R.settings);view.innerHTML=`<section class="panel"><h2>Deployment settings</h2><p class="muted">Configure provider endpoints, model names and credentials in the private environment file, then restart the backend. Secrets are never returned to this browser.</p>${table(['Setting','Value'],Object.entries(data).map(([k,v])=>`<tr><td>${e(k)}</td><td>${e(v)}</td></tr>`))}</section>`;
 }else if(page==='health'){
   const data=await api(R.health);view.innerHTML=`<div class="grid">${Object.entries(data).map(([k,v])=>`<div class="panel"><div class="eyebrow">${e(k)}</div><h2>${e(v)}</h2></div>`).join('')}</div><div class="notice amber">A healthy model endpoint confirms availability only. Run an investigation to test inference. No live executor has been verified in this release.</div>`;
 }
 bind(view);bind(actions);
 }catch(err){view.innerHTML=errorBox(err);if(err.status===401){user=null;await authScreen();}}
}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;}
function incidentTable(items){return table(['Incident / source','Priority','Mode','Status'],items.map(i=>`<tr><td class="truncate"><a href="#" data-incident="${e(i.id)}">${e(i.title)}</a><div class="mono muted">${e(i.source_id)} / ${e(i.external_id)}</div></td><td>${badge(i.priority)}</td><td>${badge(i.data_mode)}</td><td>${e(i.status)}</td></tr>`));}
function eventTable(items){return table(['Evidence','Source / ID','Mode','Event time'],items.map(i=>`<tr><td class="truncate"><a href="#" data-event="${e(i.id)}">${e(i.summary??'UNKNOWN: no summary')}</a></td><td class="mono">${e(i.source_id)}<br>${e(i.external_id)}</td><td>${badge(i.data_mode)}</td><td>${e(date(i.event_time))}</td></tr>`));}
function runTable(items){return table(['Investigation','Provider','Mode','Validation / state'],items.map(i=>`<tr><td><a href="#" class="mono" data-run="${e(i.run_id)}">${e(i.run_id.slice(0,20))}…</a><div class="small muted">${e(date(i.created_at))}</div></td><td>${e(i.provider)}<br><span class="muted small">${e(i.model)}</span></td><td>${badge(i.data_mode)}</td><td>${badge(i.status)}<div class="small">${e(i.validation_status)} · ${i.trusted?'citations checked':'untrusted/unavailable'}</div></td></tr>`));}
function actionTable(items){return table(['Action / target','Approval','Execution','Scope'],items.map(i=>`<tr><td><a href="#" data-action="${e(i.proposal_id)}">${e(i.action_type)}</a><div class="mono muted">${e(i.target)}</div></td><td>${badge(i.approval_status)}</td><td>${badge(i.status)}</td><td>${badge(i.dry_run?'DRY RUN':'REAL')}<div class="small muted">${e(i.effect_scope)}</div></td></tr>`));}
function auditTable(items){return table(['Timestamp','Action','Actor','Details'],items.map(i=>`<tr><td>${e(date(i.created_at))}</td><td>${e(i.action)}</td><td class="mono">${e(i.actor)}</td><td class="truncate mono">${e(JSON.stringify(i.detail))}</td></tr>`));}
function assetTable(items){return table(['Asset','Role / criticality','Addresses','Mode'],items.map(i=>`<tr><td>${e(i.asset_id)}</td><td>${e(i.role)} / ${e(i.criticality)}</td><td class="mono">${e(i.addresses.join(', ')||'UNKNOWN')}</td><td>${badge(i.data_mode)}</td></tr>`));}
function userTable(items){return table(['User','Role','Status','Manage'],items.map(i=>`<tr><td>${e(i.name)}</td><td>${badge(i.role)}</td><td>${i.active?'Active':'Disabled'}</td><td>${i.id!==user.id?`<button class="btn" data-user="${e(i.id)}" data-role="${e(i.role)}" data-active="${i.active}">Edit</button>`:'Current account'}</td></tr>`));}
function bind(el){
 el.querySelectorAll('[data-incident]').forEach(a=>a.onclick=ev=>{ev.preventDefault();showIncident(a.dataset.incident).catch(err=>toast(err.message));});
 el.querySelectorAll('[data-event]').forEach(a=>a.onclick=async ev=>{ev.preventDefault();try{modal('Evidence and provenance',pretty(await api(R.events+'/'+encodeURIComponent(a.dataset.event))));}catch(err){toast(err.message);}});
 el.querySelectorAll('[data-run]').forEach(a=>a.onclick=ev=>{ev.preventDefault();showRun(a.dataset.run).catch(err=>toast(err.message));});
 el.querySelectorAll('[data-action]').forEach(a=>a.onclick=ev=>{ev.preventDefault();showAction(a.dataset.action).catch(err=>toast(err.message));});
 el.querySelectorAll('[data-user]').forEach(a=>a.onclick=()=>editUser(a.dataset));
 el.querySelectorAll('[data-do]').forEach(b=>b.onclick=()=>runButton(b,async()=>{const d=b.dataset.do;if(d==='demo'){await api(R.demo,{method:'POST'});toast('TEST exercise loaded. No REAL data was created.');await load();}else if(d==='user')userForm();else if(d==='asset')assetForm();else ingestForm(d);}));
}
async function showIncident(id){
 const data=await api(R.incidents+'/'+encodeURIComponent(id));
 const d=modal('Incident investigation',`${badge(data.data_mode)} ${badge(data.priority)}<h3 style="margin-top:16px">${e(data.summary)}</h3><p class="mono muted">${e(id)}</p><div class="actions">${can(user.role,'investigate')?'<button class="btn primary" id="analyze">Run AI investigation</button><button class="btn" id="propose">Draft SOAR proposal</button>':''}</div><div class="notice amber">${e(data.missing_telemetry.join(' · ')||'No missing telemetry declared; this is not proof of complete coverage.')}</div><h3>Linked evidence</h3>${data.evidence.length?table(['Source','Observation','Priority'],data.evidence.map(x=>`<tr><td>${e(x.source)}</td><td class="truncate">${e(x.summary)}<div><a href="#" data-event="${e(x.event_uid)}">Inspect evidence →</a></div></td><td>${badge(x.priority)}</td></tr>`)):empty('No linked evidence','No conclusion about malicious activity can be drawn from absence of telemetry.')}`);
 if(can(user.role,'investigate')){d.querySelector('#analyze').onclick=ev=>runButton(ev.currentTarget,async()=>{const run=await api(R.analyze,{method:'POST',body:{incident_id:id}});d.close();await showRun(run.run_id);});d.querySelector('#propose').onclick=()=>{d.close();proposalForm(id);};}bind(d);
}
async function showRun(id){
 const data=await api(R.runs+'/'+encodeURIComponent(id));document.querySelector('#detail')?.close();
 const sections=[['observed_facts','Observed facts'],['hypotheses','Hypotheses'],['missing_evidence','Missing evidence'],['recommended_investigation','Next investigation steps'],['containment_options','Advisory containment options']];
 const d=modal('AI investigation',`${badge(data.data_mode)} ${badge(data.provider==='mock'?'TEST PROVIDER':data.provider)} ${badge(data.status)}<div class="notice amber"><strong>${data.trusted?'Citation validation passed.':'Result unavailable or validation did not pass.'}</strong> This is not semantic proof. Human review is required. AI cannot approve or execute an action.</div><div class="stack">${sections.map(([key,title])=>`<section><h3>${title}</h3>${data[key]?`<ul>${data[key].map(x=>`<li>${e(typeof x==='string'?x:x.text)}${x.limitations?`<div class="muted small">${e(x.limitations)}</div>`:''}${x.evidence_event_ids?`<div>${x.evidence_event_ids.map(c=>`<a class="mono" href="#" data-event="${e(c)}">${e(c.slice(0,22))}…</a>`).join(' · ')}</div>`:''}</li>`).join('')}</ul>`:'<p class="muted">Unavailable</p>'}</section>`).join('')}</div><details><summary>Safe run metadata and validation</summary>${pretty({run_id:data.run_id,provider:data.provider,model:data.model,validation:data.validation,error_code:data.error_code,steps:data.steps})}</details>`);bind(d);
}
async function proposalForm(incidentId){
 const books=(await api(R.playbooks)).items;
 const d=modal('Draft a DRY-RUN proposal',`<div class="notice">Simulation only. A different Operator must approve before execution.</div><form id="proposal-form"><label>Incident ID<input name="incident_id" value="${e(incidentId)}" readonly></label><label>Playbook<select name="playbook_id">${books.map(b=>`<option value="${e(b.id)}" data-type="${e(b.action_type)}">${e(b.name)}</option>`).join('')}</select></label><label>Target IP or registered TEST asset<input name="target" required placeholder="192.0.2.25"></label><label>Test process name (only for process suspension)<input name="process_name" placeholder="test-example"></label><label>Expires in minutes<input name="ttl_minutes" type="number" min="1" max="1440" value="60"></label><button class="btn primary">Submit proposal for review</button></form>`);
 d.querySelector('form').onsubmit=ev=>{ev.preventDefault();runButton(ev.currentTarget.querySelector('button'),async()=>{const f=ev.currentTarget??d.querySelector('form');const body=Object.fromEntries(new FormData(f));body.action_type=books.find(b=>b.id===body.playbook_id).action_type;body.parameters=body.action_type==='SUSPEND_TEST_PROCESS'?{process_name:body.process_name,lab_only:true}:{};delete body.process_name;body.ttl_minutes=Number(body.ttl_minutes);const result=await api(R.actions,{method:'POST',body});d.close();await showAction(result.proposal_id);});};
}
async function showAction(id){
 const a=await api(R.actions+'/'+encodeURIComponent(id));document.querySelector('#detail')?.close();
 const eligible=a.status==='PROPOSED'&&a.requested_by!==user.id&&can(user.role,'approve');
 const controls=(eligible?['approve','reject']:[]).concat(a.status==='APPROVED'&&can(user.role,'execute')?['execute']:[],a.rollback_available&&can(user.role,'rollback')?['rollback']:[]);
 const d=modal('SOAR action review',`${badge(a.status)} ${badge(a.dry_run?'DRY RUN':'REAL')}<div class="notice amber">${e(actionLabel(a))}</div><div class="form-grid"><div><h3>${e(a.action_type)}</h3><p class="mono">${e(a.target)}</p></div><div><h3>Independent approval</h3><p>${e(a.approval_status)}</p></div></div><p class="small muted">Requested by ${e(a.requested_by)}<br>Approved by ${e(a.approved_by??'Not approved')}<br>Expires ${e(date(a.expires_at))}</p><div class="grid"><div class="panel">Effect verification<br><strong>${a.verification_result===null?'UNKNOWN':a.verification_result?'Verified':'Not verified'}</strong></div><div class="panel">Restoration verification<br><strong>${a.restoration_verified===null?'UNKNOWN':a.restoration_verified?'Verified':'Not verified'}</strong></div></div><div class="flow"><span>Proposal</span>→<span>Approval</span>→<span>Execution</span>→<span>Verification</span>→<span>Rollback</span>→<span>Restoration</span></div>${eligible?'<label>Review reason<input id="decision-reason" maxlength="1000"></label>':''}<div class="actions">${controls.map(x=>`<button class="btn ${x==='approve'||x==='execute'?'primary':''}" data-operation="${x}">${x==='execute'?'Execute simulation':x==='rollback'?'Rollback simulation':x==='approve'?'Approve':'Reject'}</button>`).join('')}</div><details style="margin-top:20px"><summary>Execution receipts and audit</summary>${pretty({executions:a.executions,audit:a.audit,audit_truncated:a.audit_truncated})}</details>`);
 d.querySelectorAll('[data-operation]').forEach(b=>b.onclick=()=>runButton(b,async()=>{const op=b.dataset.operation;await api(`${R.actions}/${encodeURIComponent(id)}/${op}`,{method:'POST',...(['approve','reject'].includes(op)?{body:{reason:d.querySelector('#decision-reason').value}}:{})});d.close();await showAction(id);}));
}
function userForm(){const d=modal('Create a separate user',`<p class="muted">Analysts investigate and propose. Operators approve and execute. Admins manage access. Viewers are read-only.</p><form><label>Username<input name="name" required pattern="[A-Za-z0-9_.:-]+" maxlength="128"></label><label>Role<select name="role">${['viewer','analyst','operator','admin'].map(v=>`<option>${v}</option>`).join('')}</select></label><label>Password · at least 14 characters<input name="password" type="password" required minlength="14" maxlength="256" autocomplete="new-password"></label><button class="btn primary">Create user</button></form>`);formSubmit(d,async body=>{await api(R.users,{method:'POST',body});toast('User created. Deliver the password through a secure channel.');});}
function editUser(data){const d=modal('Change access',`<form><label>Role<select name="role">${['viewer','analyst','operator','admin'].map(v=>`<option ${v===data.role?'selected':''}>${v}</option>`).join('')}</select></label><label>Status<select name="active"><option value="true" ${data.active==='true'?'selected':''}>Active</option><option value="false" ${data.active==='false'?'selected':''}>Disabled</option></select></label><p class="muted">Existing browser sessions are revoked. The backend rechecks approval eligibility before execution.</p><button class="btn primary">Save access</button></form>`);formSubmit(d,body=>api(R.users+'/'+encodeURIComponent(data.user),{method:'PATCH',body:{role:body.role,active:body.active==='true'}}));}
function formSubmit(d,fn){d.querySelector('form').onsubmit=ev=>{ev.preventDefault();const form=ev.currentTarget;runButton(form.querySelector('button'),async()=>{await fn(Object.fromEntries(new FormData(form)));form.reset();d.close();await load();});};}
function ingestForm(kind){const incident=kind==='ingestIncidents';const sample=incident?{incidents:[{source_id:'example',external_id:'incident-1',title:'Example incident',data_mode:'TEST',events:[{source_id:'example',external_id:'event-1'}]}]}:{events:[{source_id:'example',external_id:'event-1',event_time:'2026-01-01T12:00:00Z',summary:'TEST example observation',data_mode:'TEST',priority:'UNKNOWN'}]};const d=modal(incident?'Ingest incident':'Ingest evidence',`<p class="muted">Use stable source IDs. Identical retries are safe; conflicting content returns 409. Tenant scope comes from your account. Event references must already exist.</p><form><label>Version 1 normalized JSON<textarea name="payload" rows="15" required>${e(JSON.stringify(sample,null,2))}</textarea></label><button class="btn primary">Validate and ingest</button></form>`);formSubmit(d,async body=>{const result=await api(R[kind],{method:'POST',body:JSON.parse(body.payload)});toast(`${result.items.length} records accepted`);});}
function assetForm(){const d=modal('Register inventory',`<form><label>Asset ID<input name="asset_id" required maxlength="128"></label><label>Role<input name="role" placeholder="endpoint, firewall, domain_controller…" maxlength="100"></label><label>Criticality<select name="criticality">${['unknown','low','medium','high','critical'].map(v=>`<option>${v}</option>`).join('')}</select></label><label>Data mode<select name="data_mode">${['UNKNOWN','TEST','REAL','REPLAY'].map(v=>`<option>${v}</option>`).join('')}</select></label><label>Addresses (comma separated)<input name="addresses"></label><label>Aliases (comma separated)<input name="aliases"></label><label>Registered test process asset<select name="lab_asset"><option value="false">No</option><option value="true">Yes — TEST mode required</option></select></label><button class="btn primary">Save inventory</button></form>`);formSubmit(d,body=>api(R.assets+'/'+encodeURIComponent(body.asset_id),{method:'PUT',body:{...body,role:body.role||null,addresses:body.addresses.split(',').map(s=>s.trim()).filter(Boolean),aliases:body.aliases.split(',').map(s=>s.trim()).filter(Boolean),lab_asset:body.lab_asset==='true'}}));}
window.addEventListener('hashchange',()=>{if(user)navigate();});
try{user=(await api(R.me)).user;await navigate();}catch{await authScreen();}
